version: "3.8"  # You can remove this line to avoid warnings

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      mynetwork:
        ipv4_address: 192.168.100.2  # Update to a fixed IP in your new subnet

  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8090:8090"
    volumes:
      - .m2:/root/.m2
    networks:
      mynetwork:
        ipv4_address: 192.168.100.3  # Update to a different fixed IP in your new subnet

volumes:
  db:

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24  # Use your new non-overlapping subnet 192.168.100.2